plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neo_version

    runs {
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation("net.dv8tion:JDA:5.6.1") {
        exclude module: 'opus-java'
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    runtimeOnly("net.dv8tion:JDA:5.6.1") {
        exclude module: 'opus-java'
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    runtimeOnly("com.squareup.okhttp3:okhttp:4.12.0")
    runtimeOnly("com.squareup.okio:okio-jvm:3.6.0")
    runtimeOnly("com.neovisionaries:nv-websocket-client:2.14")
    runtimeOnly("net.sf.trove4j:core:3.1.0")
    runtimeOnly("com.fasterxml.jackson.core:jackson-core:2.18.3")
    runtimeOnly("com.fasterxml.jackson.core:jackson-annotations:2.18.3")
    runtimeOnly("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    runtimeOnly("org.apache.commons:commons-collections4:4.4")
    runtimeOnly("org.jetbrains.kotlin:kotlin-stdlib:1.9.10")
    runtimeOnly("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10")
    runtimeOnly("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10")
    jarJar("net.dv8tion:JDA:5.6.1") {
        exclude module: 'opus-java'
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    jarJar("com.squareup.okhttp3:okhttp:4.12.0")
    jarJar("com.squareup.okio:okio-jvm:3.6.0")
    jarJar("com.neovisionaries:nv-websocket-client:2.14")
    jarJar("net.sf.trove4j:core:3.1.0")
    jarJar("com.fasterxml.jackson.core:jackson-core:2.18.3")
    jarJar("com.fasterxml.jackson.core:jackson-annotations:2.18.3")
    jarJar("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    jarJar("org.apache.commons:commons-collections4:4.4")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib:1.9.10")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10")
}

processResources {
    var replaceProperties = [
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}
